-- MySQL Script generated by MySQL Workbench
-- Sat Jan 16 19:22:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `notes` ;

-- -----------------------------------------------------
-- Schema notes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notes` DEFAULT CHARACTER SET utf8 ;
USE `notes` ;

-- -----------------------------------------------------
-- Table `notes`.`notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notes`.`notas` ;

CREATE TABLE IF NOT EXISTS `notes`.`notas` (
  `id_notes` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `text` TEXT(500) NULL,
  PRIMARY KEY (`id_notes`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
